name: seydirehberim
description: "Seydi Rehber - Seydişehir Rehber Uygulaması"
publish_to: 'none'
version: 1.0.0+16

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter

  # Backend
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  supabase_flutter: ^2.0.0

  # State & Routing
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.0

  # UI/UX
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.1

  # Tools
  webview_flutter: ^4.0.0
  url_launcher: ^6.0.0
  share_plus: ^10.0.0
  shared_preferences: ^2.2.0
  in_app_review: ^2.0.0
  http: ^1.0.0
  xml2json: ^6.0.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geocoding: ^3.0.0

  # Google Sign In
  google_sign_in: ^6.0.0
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3

  # Image Picker for Admin
  image_picker: ^1.1.0
  font_awesome_flutter: ^11.0.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  intl: ^0.20.2
  package_info_plus: any
  in_app_update: ^4.2.5
  animations: ^2.1.2
  like_button: ^2.1.0
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^21.0.0
  permission_handler: ^12.0.1
  googleapis_auth: ^2.0.0
  flutter_dotenv: ^6.0.0
  geolocator: ^13.0.0
  location: ^6.0.2
  timezone: ^0.11.0
  lottie: ^3.1.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: any
  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/SeydiRehber.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - .env

  fonts:
    - family: Nickainley
      fonts:
        - asset: assets/fonts/Nickainley.otf
